apiVersion: v1
kind: Service
metadata:
  name: node-svc-public
spec:
  type: NodePort
  selector:
    app: node-svc
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30100
---

